### ISSUE TITLE
Arxivar la web a l'històric

### ISSUE THREAD

**Issue by alexm** [per-la-publica/web-per-la-publica#10]
Fer una foto de la web actual abans de fer-hi canvis i arxivar-la a la secció d'històric.

**Comment by fmorillas** [comment]
Fet.
Feu revisió per trobar errades abans de fer els canvis a la web actual.

**Comment by alexm** [comment]
He fet una revisió ràpida i en principi ho veig bé.

**Comment by alexm** [comment]
Ja vam publicar els nous històrics la setmana passada.
